//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Dev/Thijs/action maps/playerjoiner.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Dev/Thijs/action maps/playerjoiner.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Playerjoiner: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Playerjoiner()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""playerjoiner"",
    ""maps"": [
        {
            ""name"": ""PlayerInputManager"",
            ""id"": ""b26a98a7-d827-4f23-9567-e90dd2a51ed4"",
            ""actions"": [
                {
                    ""name"": ""JoinPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""688fc7a9-f963-417d-9c5f-e16ba68c6b79"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnPlayerJoined"",
                    ""type"": ""Button"",
                    ""id"": ""28e553ef-c781-4261-914d-aa1b8afcbfdb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnPlayerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""fd9747a5-7058-401c-a332-a413f34d3de9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""825808d0-ef06-4aa8-b575-632165af60ae"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";contorler"",
                    ""action"": ""JoinPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e184af00-64b0-41e1-a54b-7253ad8b29ee"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard"",
                    ""action"": ""JoinPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76770df0-a89a-4a4d-a0a7-d99dc4d8d46d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnPlayerJoined"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2da4b93a-6c50-4a74-aa64-826fa07d58e0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnPlayerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""contorler"",
            ""bindingGroup"": ""contorler"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""keyboard"",
            ""bindingGroup"": ""keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerInputManager
        m_PlayerInputManager = asset.FindActionMap("PlayerInputManager", throwIfNotFound: true);
        m_PlayerInputManager_JoinPlayer = m_PlayerInputManager.FindAction("JoinPlayer", throwIfNotFound: true);
        m_PlayerInputManager_OnPlayerJoined = m_PlayerInputManager.FindAction("OnPlayerJoined", throwIfNotFound: true);
        m_PlayerInputManager_OnPlayerLeft = m_PlayerInputManager.FindAction("OnPlayerLeft", throwIfNotFound: true);
    }

    ~@Playerjoiner()
    {
        UnityEngine.Debug.Assert(!m_PlayerInputManager.enabled, "This will cause a leak and performance issues, Playerjoiner.PlayerInputManager.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputManager
    private readonly InputActionMap m_PlayerInputManager;
    private List<IPlayerInputManagerActions> m_PlayerInputManagerActionsCallbackInterfaces = new List<IPlayerInputManagerActions>();
    private readonly InputAction m_PlayerInputManager_JoinPlayer;
    private readonly InputAction m_PlayerInputManager_OnPlayerJoined;
    private readonly InputAction m_PlayerInputManager_OnPlayerLeft;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerInputManager".
    /// </summary>
    public struct PlayerInputManagerActions
    {
        private @Playerjoiner m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerInputManagerActions(@Playerjoiner wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputManager/JoinPlayer".
        /// </summary>
        public InputAction @JoinPlayer => m_Wrapper.m_PlayerInputManager_JoinPlayer;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputManager/OnPlayerJoined".
        /// </summary>
        public InputAction @OnPlayerJoined => m_Wrapper.m_PlayerInputManager_OnPlayerJoined;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputManager/OnPlayerLeft".
        /// </summary>
        public InputAction @OnPlayerLeft => m_Wrapper.m_PlayerInputManager_OnPlayerLeft;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputManager; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerInputManagerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerInputManagerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerInputManagerActions" />
        public void AddCallbacks(IPlayerInputManagerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputManagerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputManagerActionsCallbackInterfaces.Add(instance);
            @JoinPlayer.started += instance.OnJoinPlayer;
            @JoinPlayer.performed += instance.OnJoinPlayer;
            @JoinPlayer.canceled += instance.OnJoinPlayer;
            @OnPlayerJoined.started += instance.OnOnPlayerJoined;
            @OnPlayerJoined.performed += instance.OnOnPlayerJoined;
            @OnPlayerJoined.canceled += instance.OnOnPlayerJoined;
            @OnPlayerLeft.started += instance.OnOnPlayerLeft;
            @OnPlayerLeft.performed += instance.OnOnPlayerLeft;
            @OnPlayerLeft.canceled += instance.OnOnPlayerLeft;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerInputManagerActions" />
        private void UnregisterCallbacks(IPlayerInputManagerActions instance)
        {
            @JoinPlayer.started -= instance.OnJoinPlayer;
            @JoinPlayer.performed -= instance.OnJoinPlayer;
            @JoinPlayer.canceled -= instance.OnJoinPlayer;
            @OnPlayerJoined.started -= instance.OnOnPlayerJoined;
            @OnPlayerJoined.performed -= instance.OnOnPlayerJoined;
            @OnPlayerJoined.canceled -= instance.OnOnPlayerJoined;
            @OnPlayerLeft.started -= instance.OnOnPlayerLeft;
            @OnPlayerLeft.performed -= instance.OnOnPlayerLeft;
            @OnPlayerLeft.canceled -= instance.OnOnPlayerLeft;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerInputManagerActions.UnregisterCallbacks(IPlayerInputManagerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerInputManagerActions.UnregisterCallbacks(IPlayerInputManagerActions)" />
        public void RemoveCallbacks(IPlayerInputManagerActions instance)
        {
            if (m_Wrapper.m_PlayerInputManagerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerInputManagerActions.AddCallbacks(IPlayerInputManagerActions)" />
        /// <seealso cref="PlayerInputManagerActions.RemoveCallbacks(IPlayerInputManagerActions)" />
        /// <seealso cref="PlayerInputManagerActions.UnregisterCallbacks(IPlayerInputManagerActions)" />
        public void SetCallbacks(IPlayerInputManagerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputManagerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputManagerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerInputManagerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerInputManagerActions @PlayerInputManager => new PlayerInputManagerActions(this);
    private int m_contorlerSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme contorlerScheme
    {
        get
        {
            if (m_contorlerSchemeIndex == -1) m_contorlerSchemeIndex = asset.FindControlSchemeIndex("contorler");
            return asset.controlSchemes[m_contorlerSchemeIndex];
        }
    }
    private int m_keyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme keyboardScheme
    {
        get
        {
            if (m_keyboardSchemeIndex == -1) m_keyboardSchemeIndex = asset.FindControlSchemeIndex("keyboard");
            return asset.controlSchemes[m_keyboardSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerInputManager" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerInputManagerActions.AddCallbacks(IPlayerInputManagerActions)" />
    /// <seealso cref="PlayerInputManagerActions.RemoveCallbacks(IPlayerInputManagerActions)" />
    public interface IPlayerInputManagerActions
    {
        /// <summary>
        /// Method invoked when associated input action "JoinPlayer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJoinPlayer(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnPlayerJoined" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnPlayerJoined(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnPlayerLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnPlayerLeft(InputAction.CallbackContext context);
    }
}
